name: Java CI for To-Do List API

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd to-do-list-api
          mvn clean install --no-transfer-progress

      - name: Run Tests
        run: |
          cd to-do-list-api
          mvn test --no-transfer-progress